version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3030:3030"
    volumes:
      - ./backend/src:/src/src
      - ./backend/src/photos:/src/photos
    restart: unless-stopped
  frontend:
    build: ./frontend
    ports:
      - "3031:80"
    volumes:
      - ./frontend:/app
    restart: unless-stopped
