version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "9000:9000"
    volumes:
      - ./backend/src:/src/src
    restart: unless-stopped
  frontend:
    build: ./frontend
    ports:
      - "9001:80"
    volumes:
      - ./frontend:/app
    restart: unless-stopped
